version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT_FRONT}:${PORT_FRONT}'
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - network1
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_WS_API_URL}
      NEXT_PUBLIC_WS_API_URL: ${NEXT_PUBLIC_WS_API_URL}
    depends_on:
      - backend
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      # MongoDB
      MONGODB_URI: mongodb://mongodb:27017/pet-media-manager

      # AWS S3
      AWS_URL: ${AWS_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_BUCKET_PREFIX: ${AWS_BUCKET_PREFIX}

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}

      # Server
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - mongodb
    networks:
      - network1

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - network1
networks:
  network1:

volumes:
  mongodb_data:
  letsencrypt: